# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VivadoProjects/mips_pipeline/mips_pipeline.cache/wt [current_project]
set_property parent.project_path D:/VivadoProjects/mips_pipeline/mips_pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VivadoProjects/mips_pipeline/mips_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/RegBlock.vhd
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/ALU.vhd
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/RAM.vhd
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/IDecode.vhd
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/MPG.vhd
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/IFC.vhd
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/SSD.vhd
  D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/sources_1/imports/new/lab4.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/constrs_1/imports/new/netlistl1.xdc
set_property used_in_implementation false [get_files D:/VivadoProjects/mips_pipeline/mips_pipeline.srcs/constrs_1/imports/new/netlistl1.xdc]


synth_design -top lab4 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab4.dcp

catch { report_utilization -file lab4_utilization_synth.rpt -pb lab4_utilization_synth.pb }
